<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Version>2.0.0</Version>
    <Authors>Julio Cezar da Silva</Authors>
    <Description>WorkflowNet,C.Core provides base objects for WorkflowNet.</Description>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorkflowNet.Core\WorkflowNet.Core.csproj" />
  </ItemGroup>

</Project>
